#!/bin/bash
# var
python main.py --activation relu --epoch 10 --network GMM_MEDIUM --dataset GMM_CIRCLE --init_type orthogonal --gmm_cluster 4 --gmm_scale 2 --gmm_dim 2 --sample_size 512 --batch_size 512 --is_train 1 --is_crop False --g_heruistic 0 --g_update 1 --z_dim 256 --c_dim 1 --visualize_interval 50 --learning_rate_d 1e-4 --learning_rate_g 1e-4 --log_dir logs_medium_relu_c_4_orth --sample_dir samples_medium_relu_c_4_orth --checkpoint_dir checkpoint_medium_relu_c_4_orth --gmm_var 0.02
