#!/bin/bash
# Linear activation (epoch 50 or 200)
python ../main.py --activation lin --epoch 50 --network GMM_MEDIUM --dataset GMM_CIRCLE --init_type xavier --gmm_cluster 4 --gmm_scale 2 --gmm_dim 2 --sample_size 512 --batch_size 512 --is_train 1 --is_crop False --g_heuristic 0 --g_update 1 --z_dim 256 --c_dim 1 --visualize_interval 100 --learning_rate_d 1e-4 --learning_rate_g 1e-4 --log_dir logs_medium_lin_c_4_xavier --sample_dir samples_medium_lin_c_4_xavier --checkpoint_dir checkpoint_medium_lin_c_4_xavier_JS --gmm_var 0.02

# Relu activation (epoch 50 or 200)
#python ../main.py --activation relu --epoch 50 --network GMM_MEDIUM --dataset GMM_CIRCLE --init_type xavier --gmm_cluster 4 --gmm_scale 2 --gmm_dim 2 --sample_size 512 --batch_size 512 --is_train 1 --is_crop False --g_heuristic 0 --g_update 1 --z_dim 256 --c_dim 1 --visualize_interval 100 --learning_rate_d 1e-4 --learning_rate_g 1e-4 --log_dir logs_medium_relu_c_4_xavier --sample_dir samples_medium_relu_c_4_xavier --checkpoint_dir checkpoint_medium_relu_c_4_xavier_JS --gmm_var 0.02

# Tanh activation (epoch 50 or 200)
#python ../main.py --activation tanh --epoch 50 --network GMM_MEDIUM --dataset GMM_CIRCLE --init_type xavier --gmm_cluster 4 --gmm_scale 2 --gmm_dim 2 --sample_size 512 --batch_size 512 --is_train 1 --is_crop False --g_heuristic 0 --g_update 1 --z_dim 256 --c_dim 1 --visualize_interval 100 --learning_rate_d 1e-4 --learning_rate_g 1e-4 --log_dir logs_medium_tanh_c_4_xavier --sample_dir samples_medium_tanh_c_4_xavier --checkpoint_dir checkpoint_medium_tanh_c_4_xavier_JS --gmm_var 0.02
